version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/production/django/DockerFile
    command: /start
    container_name: django-api
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    depends_on:
      - postgres
      - redis
    networks:
      - devops_proj

  redis:
    image: redis:6-alpine
    container_name: redis
    networks:
      - devops_proj

  worker:
    build:
      context: .
      dockerfile: ./docker/production/django/DockerFile
    command: /start_worker
    container_name: worker
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    depends_on:
      - postgres
      - redis
    networks:
      - devops_proj

  beatworker:
    build:
      context: .
      dockerfile: ./docker/production/django/DockerFile
    command: /start_beat
    container_name: beat
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    depends_on:
      - postgres
      - redis
    networks:
      - devops_proj

  flower:
    build:
      context: .
      dockerfile: ./docker/production/django/DockerFile
    command: /start_flower
    container_name: flower
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "5555:5555"
    depends_on:
      - postgres
      - redis
    networks:
      - devops_proj

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - devops_proj

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - api
    networks:
      - devops_proj

networks:
  devops_proj:
    driver: bridge

volumes:
  production_postgres_data: {}
  static_volume:
  media_volume:
    